#!/bin/bash
mylatex ~/GIT/realAnalysis/definitions.tex
git add definitions.tex
git commit -m "auto commit"
git push origin master
scp ~/GIT/realAnalysis/definitions.pdf ottodownload@nicholasotto.com:~/html/math/definitions.pdf

