#!/bin/bash
git add ~/linux-3.2/arch/x86/include/asm/unistd_64.h
git add ~/linux-3.2/include/asm-generic/syscalls.h
git add ~/linux-3.2/include/linux/event_header.h
git add ~/linux-3.2/kernel/event.c
git add ~/linux-3.2/kernel/Makefile
git add ~/linux-3.2/init/main.c
